version: '3.7'

services:

  postgres:
    container_name: kanbanboard
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kanbanboard
      POSTGRES_PASSWORD: kanbanboard
