micronaut:
  application:
    name: kanbanboard

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/kabanboard
    driverClassName: org.postgresql.Driver
    username: kabanboard
    password: kabanboard
