micronaut:
  application:
    name: kanbanboard

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/kanbanboard
    driverClassName: org.postgresql.Driver
    username: kanbanboard
    password: kanbanboard

flyway:
  datasources:
    default:
      enabled: true
